Repository bcgov/nr-results-exam, pull requests merged in 2023-10, with the labels that each got.

#42 feat: backend URL
  docker-compose.yml
  frontend/.env
  frontend/Caddyfile
  frontend/openshift.deploy.yml
  frontend/src/services/EmailService.ts
  test.out
Labels: enhancement

#43 removed cors from express
  backend/index.js
  docker-compose.yml
  frontend/Caddyfile
  frontend/openshift.deploy.yml
Labels: enhancement

#49 ci: Disable Dependabot PR deps for Renovate
  .github/dependabot.yml
Labels: dependencies, github_actions

#51 fix: caddy in docker compose
  docker-compose.yml
Labels: bug

#50 Test/cors local
  .gitignore
  backend/.vscode/settings.json
  backend/index.js
  backend/routes/healthRoutes.js
  backend/routes/indexRoutes.js
  frontend/.vscode/settings.json
Labels: enhancement

#58 ci: clip non-changing vars, simplify
  .github/workflows/merge.yml
  .github/workflows/pr-open.yml
  docker-compose.yml
  frontend/Caddyfile
  frontend/openshift.deploy.yml
  frontend/src/aws-exports.js
  frontend/src/services/EmailService.ts
Labels: enhancement

#64 bug: clean up stale var
  frontend/openshift.deploy.yml
Labels: bug

#69 fix: missing non-root user to backend
  backend/Dockerfile
Labels: bug

#70 fix: Caddy img-src
  frontend/Caddyfile
Labels: bug

#71 fix: drop quotes in Caddy img-src
  frontend/Caddyfile
Labels: bug
