Repository bcgov/nr-results-exam, pull requests merged in 2023-11, with the labels that each got.

#92 ci: renovate extends bcgov/renovate-config
  renovate.json
Labels: dependencies, github_actions

#103 removed console log for response
  .github/workflows/pr-open.yml
  backend/openshift.deploy.yml
  frontend/openshift.deploy.yml
  frontend/src/App.tsx
  frontend/src/aws-exports.js
  frontend/src/components/TestComponent.tsx
  frontend/src/questions-config.js
Labels: enhancement

#104 chore: caddyfile tweak
  frontend/Caddyfile
Labels: bug
